### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [Jeija/planether#12]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/113960487-2aa58780-9857-11eb-8f64-5006f8ad78b3.png)

thank you  
best regards to you  
William

**Comment by Jeija** [comment]
Hello William,

the error clearly has something to do with ALSA. Planether uses OpenAL for spacial audio, the error you see is produced by a call to `alcOpenDevice`, which is trying to find an ALSA audio device on your system and open it. So:
* Do you have a sound card in your system? If not, then
  - install one (even a USB sound card will do)
  - or [create a dummy ALSA device](https://www.alsa-project.org/wiki/Matrix:Module-dummy)
* If you do have a sound card but it doesn't work, try to check if it works in other applications. I don't think the bug is related to Planether. If it still doesn't work, you can modify the planether source code (mainly `src/audio.hpp` and `src/audio.cpp`) and remove all calls to OpenAL. You won't have audio then, but the game will run.

Kind regards,
Jeija
